// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZWfGM0tAPPbBTVucR5qLxdOhnCuPU84',
    appId: '1:236637483729:web:da396a11c9cfda37dccbf0',
    messagingSenderId: '236637483729',
    projectId: 'taskapp-ce88c',
    authDomain: 'taskapp-ce88c.firebaseapp.com',
    storageBucket: 'taskapp-ce88c.firebasestorage.app',
    measurementId: 'G-00ZKHQERV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR52YtJvgXgQ1YLXrh3nKNVMKz6iYqIQQ',
    appId: '1:236637483729:android:15e8ee9c8c89e4dedccbf0',
    messagingSenderId: '236637483729',
    projectId: 'taskapp-ce88c',
    storageBucket: 'taskapp-ce88c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYpsQKinO0YL_CGEQa70fgvTwZaZqz88U',
    appId: '1:236637483729:ios:85d8051189c2602cdccbf0',
    messagingSenderId: '236637483729',
    projectId: 'taskapp-ce88c',
    storageBucket: 'taskapp-ce88c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSample',
  );
}
